### PR TITLE
fixing links. removed duplicate entry.

### PR DESCRIPTION
**Pull request by CallumWalley**
Fixes problems with landing page.

### CODE REVIEW

**Review by jennan — APPROVED** [review]
Hi @CallumWalley , great job :).

I have just changed the link to Jupyter towards an internal doc, as I felt it might not be obvious to user that this redirects to another website outside of the documentation... and we have a nice support page explaining what this is.

The same could be said for MyNeSI entry (but I am not sure if we have a documentation page that just says what it is...). If you have an idea on this, please do not hesitate to redirect to a support page that would explain what it is before merging the branch.

In any case, good job, it is approved :D.

**Comment by jennan** [comment]
After discussing with @CallumWalley , we decided to open the MyNeSI block in a separate tab, to avoid closing the documentation (as it's an external website).

**Comment by jennan** [comment]
and add a little note that MyNeSI card redirects to an other/external website

**Comment by CallumWalley** [comment]
The 'MyNeSI' card is already a duplication of the 'Accounts' card, in my opinion.
I've deleted it so that the other icons in that row have a bit more space. 

Also, the card plugin being used doesn't allow setting `target="_blank"`

**Pull request merged**
